#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER */
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_BASEADDR 0x0
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_HIGHADDR 0x1ffff
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_DATA_WIDTH 0x20
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_ECC 0x0
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_FAULT_INJECT 0x0
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_CE_FAILING_REGISTERS 0x0
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_UE_FAILING_REGISTERS 0x0
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_ECC_ONOFF_REGISTER 0x0
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MBV_LOCAL_MEMORY_MBV_DATA_LMB_BRAM_CONTROLLER */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0x1ffff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XEMACLITE_NUM_INSTANCES 1

/* Definitions for peripheral MBV_AXI_ETHERNETLITE */
#define XPAR_MBV_AXI_ETHERNETLITE_COMPATIBLE "xlnx,axi-ethernetlite-3.0"
#define XPAR_MBV_AXI_ETHERNETLITE_BASEADDR 0x40e00000
#define XPAR_MBV_AXI_ETHERNETLITE_HIGHADDR 0x40e0ffff
#define XPAR_MBV_AXI_ETHERNETLITE_TX_PING_PONG 0x1
#define XPAR_MBV_AXI_ETHERNETLITE_RX_PING_PONG 0x1
#define XPAR_MBV_AXI_ETHERNETLITE_INCLUDE_MDIO 0x1
#define XPAR_MBV_AXI_ETHERNETLITE_INCLUDE_INTERNAL_LOOPBACK 0x0
#define XPAR_MBV_AXI_ETHERNETLITE_INTERRUPTS 0x8
#define XPAR_FABRIC_MBV_AXI_ETHERNETLITE_INTR 8
#define XPAR_MBV_AXI_ETHERNETLITE_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral MBV_AXI_ETHERNETLITE */
#define XPAR_XEMACLITE_0_BASEADDR 0x40e00000
#define XPAR_FABRIC_XEMACLITE_0_INTR 8
#define XPAR_XEMACLITE_0_HIGHADDR 0x40e0ffff
#define XPAR_XEMACLITE_0_COMPATIBLE "xlnx,axi-ethernetlite-3.0"
#define XPAR_XEMACLITE_0_INCLUDE_MDIO 0x1
#define XPAR_XEMACLITE_0_INCLUDE_INTERNAL_LOOPBACK 0x0
#define XPAR_XEMACLITE_0_INTERRUPTS 0x8
#define XPAR_XEMACLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XEMACLITE_0_RX_PING_PONG 0x1
#define XPAR_XEMACLITE_0_TX_PING_PONG 0x1

#define XPAR_XGPIO_NUM_INSTANCES 7

/* Definitions for peripheral MBV_AXI_GPIO_DIP_SWITCHES */
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_BASEADDR 0x40030000
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_HIGHADDR 0x4003ffff
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_INTERRUPT_PRESENT 0x1
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_IS_DUAL 0x0
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_INTERRUPTS 0x2007
#define XPAR_FABRIC_MBV_AXI_GPIO_DIP_SWITCHES_INTR 7
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_INTERRUPT_PARENT 0x41200001
#define XPAR_MBV_AXI_GPIO_DIP_SWITCHES_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral MBV_AXI_GPIO_DIP_SWITCHES */
#define XPAR_XGPIO_0_BASEADDR 0x40030000
#define XPAR_FABRIC_XGPIO_0_INTR 7
#define XPAR_XGPIO_0_HIGHADDR 0x4003ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x4
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_0_IS_DUAL 0x0
#define XPAR_XGPIO_0_INTERRUPTS 0x2007
#define XPAR_XGPIO_0_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral MBV_AXI_GPIO_IIC_PULLUPS */
#define XPAR_MBV_AXI_GPIO_IIC_PULLUPS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_MBV_AXI_GPIO_IIC_PULLUPS_BASEADDR 0x40060000
#define XPAR_MBV_AXI_GPIO_IIC_PULLUPS_HIGHADDR 0x4006ffff
#define XPAR_MBV_AXI_GPIO_IIC_PULLUPS_INTERRUPT_PRESENT 0x0
#define XPAR_MBV_AXI_GPIO_IIC_PULLUPS_IS_DUAL 0x0
#define XPAR_MBV_AXI_GPIO_IIC_PULLUPS_GPIO_WIDTH 0x2

/* Canonical definitions for peripheral MBV_AXI_GPIO_IIC_PULLUPS */
#define XPAR_XGPIO_1_BASEADDR 0x40060000
#define XPAR_XGPIO_1_HIGHADDR 0x4006ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x2
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral MBV_AXI_GPIO_LED_4_BITS */
#define XPAR_MBV_AXI_GPIO_LED_4_BITS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_MBV_AXI_GPIO_LED_4_BITS_BASEADDR 0x40040000
#define XPAR_MBV_AXI_GPIO_LED_4_BITS_HIGHADDR 0x4004ffff
#define XPAR_MBV_AXI_GPIO_LED_4_BITS_INTERRUPT_PRESENT 0x0
#define XPAR_MBV_AXI_GPIO_LED_4_BITS_IS_DUAL 0x0
#define XPAR_MBV_AXI_GPIO_LED_4_BITS_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral MBV_AXI_GPIO_LED_4_BITS */
#define XPAR_XGPIO_2_BASEADDR 0x40040000
#define XPAR_XGPIO_2_HIGHADDR 0x4004ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x4
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

/* Definitions for peripheral MBV_AXI_GPIO_LED_RGB */
#define XPAR_MBV_AXI_GPIO_LED_RGB_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_MBV_AXI_GPIO_LED_RGB_BASEADDR 0x40050000
#define XPAR_MBV_AXI_GPIO_LED_RGB_HIGHADDR 0x4005ffff
#define XPAR_MBV_AXI_GPIO_LED_RGB_INTERRUPT_PRESENT 0x0
#define XPAR_MBV_AXI_GPIO_LED_RGB_IS_DUAL 0x0
#define XPAR_MBV_AXI_GPIO_LED_RGB_GPIO_WIDTH 0xc

/* Canonical definitions for peripheral MBV_AXI_GPIO_LED_RGB */
#define XPAR_XGPIO_3_BASEADDR 0x40050000
#define XPAR_XGPIO_3_HIGHADDR 0x4005ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0xc
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x0

/* Definitions for peripheral MBV_AXI_GPIO_PUSH_BUTTONS */
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_BASEADDR 0x40020000
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_HIGHADDR 0x4002ffff
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_INTERRUPT_PRESENT 0x1
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_IS_DUAL 0x0
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_INTERRUPTS 0x2006
#define XPAR_FABRIC_MBV_AXI_GPIO_PUSH_BUTTONS_INTR 6
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_INTERRUPT_PARENT 0x41200001
#define XPAR_MBV_AXI_GPIO_PUSH_BUTTONS_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral MBV_AXI_GPIO_PUSH_BUTTONS */
#define XPAR_XGPIO_4_BASEADDR 0x40020000
#define XPAR_FABRIC_XGPIO_4_INTR 6
#define XPAR_XGPIO_4_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_4_GPIO_WIDTH 0x4
#define XPAR_XGPIO_4_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_4_IS_DUAL 0x0
#define XPAR_XGPIO_4_INTERRUPTS 0x2006
#define XPAR_XGPIO_4_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral MBV_AXI_GPIO_SHIELD_PINS_0_19 */
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_BASEADDR 0x40000000
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_HIGHADDR 0x4000ffff
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_INTERRUPT_PRESENT 0x1
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_IS_DUAL 0x0
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_INTERRUPTS 0x2004
#define XPAR_FABRIC_MBV_AXI_GPIO_SHIELD_PINS_0_19_INTR 4
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_INTERRUPT_PARENT 0x41200001
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_0_19_GPIO_WIDTH 0x14

/* Canonical definitions for peripheral MBV_AXI_GPIO_SHIELD_PINS_0_19 */
#define XPAR_XGPIO_5_BASEADDR 0x40000000
#define XPAR_FABRIC_XGPIO_5_INTR 4
#define XPAR_XGPIO_5_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_5_GPIO_WIDTH 0x14
#define XPAR_XGPIO_5_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_5_IS_DUAL 0x0
#define XPAR_XGPIO_5_INTERRUPTS 0x2004
#define XPAR_XGPIO_5_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral MBV_AXI_GPIO_SHIELD_PINS_26_41 */
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_BASEADDR 0x40010000
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_HIGHADDR 0x4001ffff
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_INTERRUPT_PRESENT 0x1
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_IS_DUAL 0x0
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_INTERRUPTS 0x2005
#define XPAR_FABRIC_MBV_AXI_GPIO_SHIELD_PINS_26_41_INTR 5
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_INTERRUPT_PARENT 0x41200001
#define XPAR_MBV_AXI_GPIO_SHIELD_PINS_26_41_GPIO_WIDTH 0x10

/* Canonical definitions for peripheral MBV_AXI_GPIO_SHIELD_PINS_26_41 */
#define XPAR_XGPIO_6_BASEADDR 0x40010000
#define XPAR_FABRIC_XGPIO_6_INTR 5
#define XPAR_XGPIO_6_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_6_GPIO_WIDTH 0x10
#define XPAR_XGPIO_6_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_6_IS_DUAL 0x0
#define XPAR_XGPIO_6_INTERRUPTS 0x2005
#define XPAR_XGPIO_6_INTERRUPT_PARENT 0x41200001

#define XPAR_XIIC_NUM_INSTANCES 1

/* Definitions for peripheral MBV_AXI_IIC */
#define XPAR_MBV_AXI_IIC_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_MBV_AXI_IIC_BASEADDR 0x40800000
#define XPAR_MBV_AXI_IIC_HIGHADDR 0x4080ffff
#define XPAR_MBV_AXI_IIC_TEN_BIT_ADR 0x0
#define XPAR_MBV_AXI_IIC_GPO_WIDTH 0x1
#define XPAR_MBV_AXI_IIC_INTERRUPTS 0x200a
#define XPAR_FABRIC_MBV_AXI_IIC_INTR 10
#define XPAR_MBV_AXI_IIC_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral MBV_AXI_IIC */
#define XPAR_XIIC_0_BASEADDR 0x40800000
#define XPAR_FABRIC_XIIC_0_INTR 10
#define XPAR_XIIC_0_HIGHADDR 0x4080ffff
#define XPAR_XIIC_0_COMPATIBLE "xlnx,axi-iic-2.1"
#define XPAR_XIIC_0_GPO_WIDTH 0x1
#define XPAR_XIIC_0_INTERRUPTS 0x200a
#define XPAR_XIIC_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XIIC_0_TEN_BIT_ADR 0x0

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MBV_AXI_INTERRUPT_CONTROLLER */
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_BASEADDR 0x41200000
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_HIGHADDR 0x4120ffff
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_KIND_OF_INTR 0x30c
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_IS_FAST 0x1
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_IVAR_RST_VAL 0x10
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_NUM_INTR_INPUTS 0xb
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_ADDR_WIDTH 0x20
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_NUM_SW_INTR 0x0
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_HAS_IVR 0x1
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_HAS_CIE 0x1
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_HAS_SIE 0x1
#define XPAR_MBV_AXI_INTERRUPT_CONTROLLER_HAS_IPR 0x1

/* Canonical definitions for peripheral MBV_AXI_INTERRUPT_CONTROLLER */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x30c
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0xb
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XSPI_NUM_INSTANCES 2

/* Definitions for peripheral MBV_AXI_QUAD_SPI */
#define XPAR_MBV_AXI_QUAD_SPI_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_MBV_AXI_QUAD_SPI_BASEADDR 0x44a10000
#define XPAR_MBV_AXI_QUAD_SPI_HIGHADDR 0x44a1ffff
#define XPAR_MBV_AXI_QUAD_SPI_HASFIFOS 0x1
#define XPAR_MBV_AXI_QUAD_SPI_SLAVEONLY 0x0
#define XPAR_MBV_AXI_QUAD_SPI_NUM_SS_BITS 0x1
#define XPAR_MBV_AXI_QUAD_SPI_BITS_PER_WORD 0x20
#define XPAR_MBV_AXI_QUAD_SPI_SPI_MODE 0x0
#define XPAR_MBV_AXI_QUAD_SPI_AXI_INTERFACE 0x1
#define XPAR_MBV_AXI_QUAD_SPI_AXI4_ADDRESS 0x44a10000
#define XPAR_MBV_AXI_QUAD_SPI_XIP_MODE 0x0
#define XPAR_MBV_AXI_QUAD_SPI_FIFO_SIZE 0x100
#define XPAR_MBV_AXI_QUAD_SPI_INTERRUPTS 0x9
#define XPAR_FABRIC_MBV_AXI_QUAD_SPI_INTR 9
#define XPAR_MBV_AXI_QUAD_SPI_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral MBV_AXI_QUAD_SPI */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x44a10000
#define XPAR_XSPI_0_BASEADDR 0x44a10000
#define XPAR_FABRIC_XSPI_0_INTR 9
#define XPAR_XSPI_0_HIGHADDR 0x44a1ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x1
#define XPAR_XSPI_0_BITS_PER_WORD 0x20
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x100
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_INTERRUPTS 0x9
#define XPAR_XSPI_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x0
#define XPAR_XSPI_0_XIP_MODE 0x0

/* Definitions for peripheral MBV_AXI_QUAD_SPI_FLASH */
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_BASEADDR 0x44a00000
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_HIGHADDR 0x44a0ffff
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_HASFIFOS 0x1
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_SLAVEONLY 0x0
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_NUM_SS_BITS 0x1
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_BITS_PER_WORD 0x8
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_SPI_MODE 0x2
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_AXI_INTERFACE 0x1
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_AXI4_ADDRESS 0x44a00000
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_XIP_MODE 0x0
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_FIFO_SIZE 0x100
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_INTERRUPTS 0x3
#define XPAR_FABRIC_MBV_AXI_QUAD_SPI_FLASH_INTR 3
#define XPAR_MBV_AXI_QUAD_SPI_FLASH_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral MBV_AXI_QUAD_SPI_FLASH */
#define XPAR_XSPI_1_AXI4_ADDRESS 0x44a00000
#define XPAR_XSPI_1_BASEADDR 0x44a00000
#define XPAR_FABRIC_XSPI_1_INTR 3
#define XPAR_XSPI_1_HIGHADDR 0x44a0ffff
#define XPAR_XSPI_1_AXI_INTERFACE 0x1
#define XPAR_XSPI_1_BITS_PER_WORD 0x8
#define XPAR_XSPI_1_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_1_FIFO_SIZE 0x100
#define XPAR_XSPI_1_HASFIFOS 0x1
#define XPAR_XSPI_1_INTERRUPTS 0x3
#define XPAR_XSPI_1_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_1_NUM_SS_BITS 0x1
#define XPAR_XSPI_1_SLAVEONLY 0x0
#define XPAR_XSPI_1_SPI_MODE 0x2
#define XPAR_XSPI_1_XIP_MODE 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral MBV_AXI_UARTLITE */
#define XPAR_MBV_AXI_UARTLITE_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_MBV_AXI_UARTLITE_BASEADDR 0x40600000
#define XPAR_MBV_AXI_UARTLITE_HIGHADDR 0x4060ffff
#define XPAR_MBV_AXI_UARTLITE_BAUDRATE 0x1c200
#define XPAR_MBV_AXI_UARTLITE_USE_PARITY 0x0
#define XPAR_MBV_AXI_UARTLITE_ODD_PARITY 0x0
#define XPAR_MBV_AXI_UARTLITE_DATA_BITS 0x8
#define XPAR_MBV_AXI_UARTLITE_INTERRUPTS 0x2
#define XPAR_FABRIC_MBV_AXI_UARTLITE_INTR 2
#define XPAR_MBV_AXI_UARTLITE_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral MBV_AXI_UARTLITE */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_FABRIC_XUARTLITE_0_INTR 2
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x2
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

#define XPAR_XWDTTB_NUM_INSTANCES 1

/* Definitions for peripheral MBV_AXI_TIMEBASE_WATCHDOG_TIMER */
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_COMPATIBLE "xlnx,axi-timebase-wdt-3.0"
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_BASEADDR 0x41a00000
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_HIGHADDR 0x41a0ffff
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_ENABLE_WINDOW_WDT 0x1
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_MAX_COUNT_WIDTH 0x20
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_SST_COUNT_WIDTH 0x8
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_INTERRUPTS 0x2001
#define XPAR_FABRIC_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_INTR 1
#define XPAR_MBV_AXI_TIMEBASE_WATCHDOG_TIMER_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral MBV_AXI_TIMEBASE_WATCHDOG_TIMER */
#define XPAR_XWDTTB_0_BASEADDR 0x41a00000
#define XPAR_FABRIC_XWDTTB_0_INTR 1
#define XPAR_XWDTTB_0_HIGHADDR 0x41a0ffff
#define XPAR_XWDTTB_0_COMPATIBLE "xlnx,axi-timebase-wdt-3.0"
#define XPAR_XWDTTB_0_ENABLE_WINDOW_WDT 0x1
#define XPAR_XWDTTB_0_INTERRUPTS 0x2001
#define XPAR_XWDTTB_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XWDTTB_0_MAX_COUNT_WIDTH 0x20
#define XPAR_XWDTTB_0_SST_COUNT_WIDTH 0x8

/*  BOARD definition */
#define XPS_BOARD_ARTY-A7-35

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x1ffff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 75000000
#define XPAR_MICROBLAZE_RISCV_FREQ 75000000
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 3
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 2
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 1
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 0
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 1073741823
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 75000000

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 0

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 0

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 3

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

#define XPAR_MICROBLAZE_RISCV_ADDR_SIZE 32

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a35ti"

#endif  /* end of protection macro */