@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Dec 23 11:34:48 +0100 2025
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim mbv_system_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:mbv_system_wrapper} -tclbatch mbv_system_wrapper.tcl -protoinst "protoinst_files/bd_e941.protoinst" -protoinst "protoinst_files/mbv_system.protoinst" -log simulate.log"
call xsim  mbv_system_wrapper_func_synth -key {Post-Synthesis:sim_1:Functional:mbv_system_wrapper} -tclbatch mbv_system_wrapper.tcl -protoinst "protoinst_files/bd_e941.protoinst" -protoinst "protoinst_files/mbv_system.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
