@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Dec 23 10:58:06 +0100 2025
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L microblaze_v11_0_16 -L microblaze_riscv_v1_0_7 -L lmb_v10_v3_0_16 -L lmb_bram_if_cntlr_v4_0_27 -L axi_lite_ipif_v3_0_4 -L axi_intc_v4_1_22 -L mdm_riscv_v1_0_7 -L proc_sys_reset_v5_0_17 -L fit_timer_v2_0_13 -L axi_timebase_wdt_v3_0_27 -L axi_uartlite_v2_0_39 -L interrupt_control_v3_1_5 -L axi_gpio_v2_0_37 -L axi_ethernetlite_v3_0_36 -L axi_iic_v2_1_11 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot mbv_system_wrapper_behav xil_defaultlib.mbv_system_wrapper xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L microblaze_v11_0_16 -L microblaze_riscv_v1_0_7 -L lmb_v10_v3_0_16 -L lmb_bram_if_cntlr_v4_0_27 -L axi_lite_ipif_v3_0_4 -L axi_intc_v4_1_22 -L mdm_riscv_v1_0_7 -L proc_sys_reset_v5_0_17 -L fit_timer_v2_0_13 -L axi_timebase_wdt_v3_0_27 -L axi_uartlite_v2_0_39 -L interrupt_control_v3_1_5 -L axi_gpio_v2_0_37 -L axi_ethernetlite_v3_0_36 -L axi_iic_v2_1_11 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot mbv_system_wrapper_behav xil_defaultlib.mbv_system_wrapper xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
