# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mbv_system/mbv_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system || ORIG_REF_NAME==mbv_system} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_microblaze_riscv_0_0/mbv_system_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_microblaze_riscv_0_0 || ORIG_REF_NAME==mbv_system_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_dlmb_v10_1/mbv_system_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_dlmb_v10_1 || ORIG_REF_NAME==mbv_system_dlmb_v10_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_ilmb_v10_1/mbv_system_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_ilmb_v10_1 || ORIG_REF_NAME==mbv_system_ilmb_v10_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_dlmb_bram_if_cntlr_1/mbv_system_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==mbv_system_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_ilmb_bram_if_cntlr_1/mbv_system_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==mbv_system_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_lmb_bram_1/mbv_system_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_lmb_bram_1 || ORIG_REF_NAME==mbv_system_lmb_bram_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/mbv_system_mbv_riscv_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_mbv_riscv_axi_periph_1 || ORIG_REF_NAME==mbv_system_mbv_riscv_axi_periph_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_mbv_riscv_axi_intc_1/mbv_system_mbv_riscv_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_mbv_riscv_axi_intc_1 || ORIG_REF_NAME==mbv_system_mbv_riscv_axi_intc_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_mdm_1_1/mbv_system_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_mdm_1_1 || ORIG_REF_NAME==mbv_system_mdm_1_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_clk_wiz_1_1/mbv_system_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_clk_wiz_1_1 || ORIG_REF_NAME==mbv_system_clk_wiz_1_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_rst_clk_wiz_1_100M_1/mbv_system_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==mbv_system_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_fit_timer_0_0/mbv_system_fit_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_fit_timer_0_0 || ORIG_REF_NAME==mbv_system_fit_timer_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_timebase_wdt_0_0/mbv_system_axi_timebase_wdt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_timebase_wdt_0_0 || ORIG_REF_NAME==mbv_system_axi_timebase_wdt_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_uartlite_0_0/mbv_system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_uartlite_0_0 || ORIG_REF_NAME==mbv_system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_quad_spi_0_0/mbv_system_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_quad_spi_0_0 || ORIG_REF_NAME==mbv_system_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_gpio_0_0/mbv_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_gpio_0_0 || ORIG_REF_NAME==mbv_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_gpio_0_1/mbv_system_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_gpio_0_1 || ORIG_REF_NAME==mbv_system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_gpio_0_2/mbv_system_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_gpio_0_2 || ORIG_REF_NAME==mbv_system_axi_gpio_0_2} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_gpio_0_3/mbv_system_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_gpio_0_3 || ORIG_REF_NAME==mbv_system_axi_gpio_0_3} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_gpio_0_4/mbv_system_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_gpio_0_4 || ORIG_REF_NAME==mbv_system_axi_gpio_0_4} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_gpio_0_5/mbv_system_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_gpio_0_5 || ORIG_REF_NAME==mbv_system_axi_gpio_0_5} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_ethernetlite_0_0/mbv_system_axi_ethernetlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_ethernetlite_0_0 || ORIG_REF_NAME==mbv_system_axi_ethernetlite_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_quad_spi_0_1/mbv_system_axi_quad_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_quad_spi_0_1 || ORIG_REF_NAME==mbv_system_axi_quad_spi_0_1} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_iic_0_0/mbv_system_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_iic_0_0 || ORIG_REF_NAME==mbv_system_axi_iic_0_0} -quiet] -quiet

# IP: bd/mbv_system/ip/mbv_system_axi_gpio_0_6/mbv_system_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbv_system_axi_gpio_0_6 || ORIG_REF_NAME==mbv_system_axi_gpio_0_6} -quiet] -quiet

# XDC: C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/mbv_system_ooc.xdc
