# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.runs/synth_1/mbv_system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
set_param chipscope.maxJobs 8
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.cache/wt [current_project]
set_property parent.project_path C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {X:/vivado-boards-master/new} [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.1 [current_project]
set_property ip_output_repo c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/hdl/mbv_system_wrapper.vhd
add_files C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.srcs/sources_1/bd/mbv_system/mbv_system.bd
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_microblaze_riscv_0_0/mbv_system_microblaze_riscv_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_microblaze_riscv_0_0/mbv_system_microblaze_riscv_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_microblaze_riscv_0_0/mbv_system_microblaze_riscv_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_dlmb_v10_1/mbv_system_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_ilmb_v10_1/mbv_system_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_dlmb_bram_if_cntlr_1/mbv_system_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_ilmb_bram_if_cntlr_1/mbv_system_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_lmb_bram_1/mbv_system_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_1/bd_e941_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_2/bd_e941_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_3/bd_e941_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_4/bd_e941_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_5/bd_e941_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_6/bd_e941_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_7/bd_e941_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_8/bd_e941_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_9/bd_e941_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_10/bd_e941_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_11/bd_e941_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_12/bd_e941_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_13/bd_e941_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_14/bd_e941_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_15/bd_e941_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_16/bd_e941_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_20/bd_e941_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_21/bd_e941_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_22/bd_e941_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_23/bd_e941_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_24/bd_e941_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_25/bd_e941_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_26/bd_e941_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_27/bd_e941_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_28/bd_e941_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_29/bd_e941_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_30/bd_e941_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_31/bd_e941_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_33/bd_e941_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_34/bd_e941_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_35/bd_e941_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_36/bd_e941_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_37/bd_e941_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_38/bd_e941_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_40/bd_e941_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_41/bd_e941_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_42/bd_e941_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_43/bd_e941_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_44/bd_e941_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_45/bd_e941_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_47/bd_e941_m03s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_48/bd_e941_m03arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_49/bd_e941_m03rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_50/bd_e941_m03awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_51/bd_e941_m03wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_52/bd_e941_m03bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_54/bd_e941_m04s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_55/bd_e941_m04arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_56/bd_e941_m04rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_57/bd_e941_m04awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_58/bd_e941_m04wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_59/bd_e941_m04bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_61/bd_e941_m05s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_62/bd_e941_m05arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_63/bd_e941_m05rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_64/bd_e941_m05awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_65/bd_e941_m05wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_66/bd_e941_m05bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_68/bd_e941_m06s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_69/bd_e941_m06arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_70/bd_e941_m06rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_71/bd_e941_m06awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_72/bd_e941_m06wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_73/bd_e941_m06bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_75/bd_e941_m07s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_76/bd_e941_m07arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_77/bd_e941_m07rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_78/bd_e941_m07awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_79/bd_e941_m07wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_80/bd_e941_m07bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_82/bd_e941_m08s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_83/bd_e941_m08arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_84/bd_e941_m08rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_85/bd_e941_m08awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_86/bd_e941_m08wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_87/bd_e941_m08bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_89/bd_e941_m09s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_90/bd_e941_m09arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_91/bd_e941_m09rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_92/bd_e941_m09awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_93/bd_e941_m09wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_94/bd_e941_m09bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_96/bd_e941_m10s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_97/bd_e941_m10arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_98/bd_e941_m10rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_99/bd_e941_m10awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_100/bd_e941_m10wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_101/bd_e941_m10bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_103/bd_e941_m11s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_104/bd_e941_m11arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_105/bd_e941_m11rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_106/bd_e941_m11awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_107/bd_e941_m11wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_108/bd_e941_m11bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_110/bd_e941_m12s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_111/bd_e941_m12arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_112/bd_e941_m12rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_113/bd_e941_m12awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_114/bd_e941_m12wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_115/bd_e941_m12bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_117/bd_e941_m13s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_118/bd_e941_m13arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_119/bd_e941_m13rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_120/bd_e941_m13awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_121/bd_e941_m13wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/bd_0/ip/ip_122/bd_e941_m13bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_periph_1/smartconnect.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_intc_1/mbv_system_mbv_riscv_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_intc_1/mbv_system_mbv_riscv_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mbv_riscv_axi_intc_1/mbv_system_mbv_riscv_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mdm_1_1/mbv_system_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mdm_1_1/mbv_system_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_mdm_1_1/mbv_system_mdm_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_clk_wiz_1_1/mbv_system_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_clk_wiz_1_1/mbv_system_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_clk_wiz_1_1/mbv_system_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_rst_clk_wiz_1_100M_1/mbv_system_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_rst_clk_wiz_1_100M_1/mbv_system_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_fit_timer_0_0/mbv_system_fit_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_timebase_wdt_0_0/mbv_system_axi_timebase_wdt_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_uartlite_0_0/mbv_system_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_uartlite_0_0/mbv_system_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_0/mbv_system_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_0/mbv_system_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_0/mbv_system_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_0/mbv_system_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_0/mbv_system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_0/mbv_system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_1/mbv_system_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_1/mbv_system_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_2/mbv_system_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_2/mbv_system_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_3/mbv_system_axi_gpio_0_3_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_3/mbv_system_axi_gpio_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_4/mbv_system_axi_gpio_0_4_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_4/mbv_system_axi_gpio_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_5/mbv_system_axi_gpio_0_5_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_5/mbv_system_axi_gpio_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_ethernetlite_0_0/mbv_system_axi_ethernetlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_ethernetlite_0_0/mbv_system_axi_ethernetlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_ethernetlite_0_0/mbv_system_axi_ethernetlite_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_ethernetlite_0_0/mbv_system_axi_ethernetlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_1/mbv_system_axi_quad_spi_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_1/mbv_system_axi_quad_spi_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_1/mbv_system_axi_quad_spi_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_quad_spi_0_1/mbv_system_axi_quad_spi_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_iic_0_0/mbv_system_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_iic_0_0/mbv_system_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_6/mbv_system_axi_gpio_0_6_board.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_axi_gpio_0_6/mbv_system_axi_gpio_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/mbv_system_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.gen/sources_1/bd/mbv_system/ip/mbv_system_microblaze_riscv_0_0/data/riscv_bootloop.elf]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/rustos/hardware/rv32imacb_zicsr_zifencei_zbc/rv32imacb_zicsr_zifencei_zbc.srcs/utils_1/imports/synth_1/mbv_system_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top mbv_system_wrapper -part xc7a35ticsg324-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mbv_system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file mbv_system_wrapper_utilization_synth.rpt -pb mbv_system_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
